### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by bresheske** [TheLX5/SMW-Patches#4]
Not sure if this is still maintained, but here's what I see when attempting to install over a ROM using ASMR.

```
retry.asm:62: error: Unknown command. [while read1($00A304+0) != $60]
retry.asm:2671: error: Misplaced endif [endif]
Errors were detected while assembling the patch. Assembling aborted. Your ROM has not been modified.
```

Perhaps I have an outdated version of ASMR, or perhaps I need to modify something?

I am using Win10, Lunar Magic for the ROM edits, and Retry v2.06c.

**Comment by TheLX5** [comment]
Sounds like you're using a **really** old version of [Asar](https://github.com/RPGHacker/asar). Try [upgrading or using a more recent version](https://github.com/RPGHacker/asar/releases/tag/v1.81) of the tool and not the one that comes bundled with any of the other tools.

**Comment by bresheske** [comment]
Thanks for the quick response! That worked like a charm.  Thanks for the help, and for putting together the retry system. 

Closing.
